name: my_wallet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^9.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_admin_scaffold: ^1.4.0
  flutter_bloc: ^9.1.1
  flutter_breadcrumb: ^1.0.1
  flutter_modular: ^6.3.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  iconsax: ^0.0.8
  intl: ^0.18.1
  loader_overlay: ^4.0.4+1
  path: ^1.9.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  rename: ^3.1.0
  responsive_framework: ^1.5.1
  sembast: ^3.7.2
  sembast_web: ^2.4.0+2
  shimmer: ^3.0.0
  supabase_flutter: ^2.9.1
  syncfusion_flutter_charts: ^27.2.5
  syncfusion_flutter_core: ^27.2.5
  syncfusion_flutter_datagrid: ^27.2.5
  syncfusion_flutter_datagrid_export: ^27.2.5
  syncfusion_flutter_datepicker: ^27.2.5
  syncfusion_flutter_pdf: ^27.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaBold.ttf
          weight: 700
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 500
        - asset: assets/fonts/LufgaRegular.ttf
          weight: 400

    - family: IconBill
      fonts:
        - asset: assets/icons/bills.ttf

    - family: IconDashboard
      fonts:
        - asset: assets/icons/dashboard.ttf

    - family: IconProfile
      fonts:
        - asset: assets/icons/profile.ttf
